name: Docker Image CI

on:
  push:
    branches: 
      - master
    tags:
      - '[0-9].[0-9]+.[0-9]+.[0-9]+'

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo ::set-output name=sha_short::$(echo ${{ github.sha }} | cut -c 1-8)
      id: vars
    - run: echo ::set-output name=tag_value::$(echo ${{ github.ref }} | cut -d / -f 3)
      id: buildtag
    - run: echo ::set-output name=tag_value::$(echo ${{ steps.vars.outputs.tag_value }} | cut -d \. -f 1-3)
      id: wptag
    - run: echo ${{ steps.vars.outputs.tag_value }}
      id: echo_vars_tag
    - run: echo ${{ steps.wptag.outputs.tag_value }}
      id: echo_wptag_tag
    - name: Build the Docker image - master with tags
      if: contains(steps.wptag.outputs.tag_value,'tags')
      uses: ilteoood/docker_buildx@master
      with:
        publish: true
        tag: ${{ steps.vars.outputs.sha_short }},${{ steps.tag.outputs.tag_value }}
        imageName: mbartsch/wordpress
        dockerHubUser: ${{ secrets.DOCKER_USERNAME }}
        dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}
        platform: linux/amd64,linux/arm64
        buildArg: WPRELASE=${{ steps.wptag.outputs.tag_value }}
    - name: Build the Docker image - master with latest
      if: ${{ steps.vars.outputs.tag_value }} == 'ref/head/master'
      uses: ilteoood/docker_buildx@master
      with:
        publish: true
        tag: latest,${{ steps.vars.outputs.sha_short }}
        imageName: mbartsch/wordpress
        dockerHubUser: ${{ secrets.DOCKER_USERNAME }}
        dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}
        platform: linux/amd64,linux/arm64
        buildArg: WPRELASE=latest
        
