name: Docker Image CI

on:
  push:
    branches: 
      - master
    tags:
      - '[0-9].[0-9]+.[0-9]+.[0-9]+'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
    - name: lint
      uses: luke142367/Docker-Lint-Action@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET: Dockerfile
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo ::set-output name=sha_short::$(echo ${{ github.sha }} | cut -c 1-8)
      id: vars
    - run: echo ::set-output name=tag_value::$(echo ${{ github.ref }} | cut -d / -f 3)
      id: buildtag
    - run: echo ::set-output name=tag_value::$(echo ${{ steps.buildtag.outputs.tag_value }} | cut -d \. -f 1-3)
      id: wptag
    - run: echo ${{ steps.vars.outputs.tag_value }}
      id: echo_vars_tag
    - run: echo ${{ steps.wptag.outputs.tag_value }}
      id: echo_wptag_tag
    - run: echo ${{ steps.buildtag.outputs.tag_value }}
      id: echo_buildtag_tag
    - name: Build the Docker image - master with tags
      if: contains(github.ref,'tags')
      uses: ilteoood/docker_buildx@master
      with:
        publish: true
        tag: ${{ steps.buildtag.outputs.tag_value }}
        imageName: mbartsch/wordpress
        dockerHubUser: ${{ secrets.DOCKER_USERNAME }}
        dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}
        platform: linux/amd64,linux/arm64
        buildArg: WPRELASE=${{ steps.wptag.outputs.tag_value }}
    - name: Build the Docker image - master with latest
      if: github.ref == 'refs/heads/master'
      uses: ilteoood/docker_buildx@master
      with:
        publish: true
        tag: latest
        imageName: mbartsch/wordpress
        dockerHubUser: ${{ secrets.DOCKER_USERNAME }}
        dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}
        platform: linux/amd64,linux/arm64
        
