name: Docker Image CI (DEVEL)

on:
  push:
    branches: 
      - devel

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo ::set-output name=sha_short::$(echo ${{ github.sha }} | cut -c 1-8)
      id: vars
    - run: echo ::set-output name=tag_value::$(echo ${{ github.ref }} | cut -d / -f 3)
      id: tag
    - name: Build the Docker image - devel
      uses: ilteoood/docker_buildx@master
      with:
        publish: true
        tag: devel,${{ steps.vars.outputs.sha_short }}-dev,${{ steps.tag.outputs.tag_value }}-dev
        imageName: mbartsch/wordpress
        dockerHubUser: ${{ secrets.DOCKER_USERNAME }}
        dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}
        platform: linux/amd64,linux/arm64
